@startuml Website Biografi
left to right direction

actor Pengunjung
actor Admin

rectangle Website_Biografi {
    Pengunjung -- (Intro)
    Pengunjung -- (Members)
    Pengunjung -- (About)
    Pengunjung -- (Contact)
    Pengunjung -- (Play/Mute Musik)

    Admin -- (Login)

    (Login) <.. (Logout) : <<extend>>
    (Login) <.. (Tambah Member) : <<extend>>
    (Login) <.. (Hapus Member) : <<extend>>
    (Login) <.. (Edit Member) : <<extend>>
    (Login) <.. (Hapus Pesan Masuk) : <<extend>>
}

@enduml